name: 🐛 Bug Report
description: Report a bug or unexpected issue with the ZED Path Planner.
title: "[BUG] "
labels: ["bug"]
assignees: ["Ashton254"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the info below so we can help.

  - type: input
    id: version
    attributes:
      label: What version are you using?
      placeholder: v1.0.0
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      placeholder: "A clear and concise description of what went wrong..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      value: |
        1.
        2.
        3.
        ...
      render: bash
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: "What should have happened instead?"

  - type: textarea
    id: screenshot
    attributes:
      label: Screenshots or logs
      placeholder: "Drag and drop screenshots here or paste error logs..."

  - type: input
    id: browser
    attributes:
      label: What browser or device are you using?
      placeholder: "e.g. Chrome on Windows 10"
