name: ✨ Feature Request
description: Suggest a new feature or idea for ZED Path Planner.
title: "[FEATURE] "
labels: ["enhancement"]
assignees: ["Ashton254"]
body:
  - type: markdown
    attributes:
      value: "Thanks for suggesting a feature! Let us know what you're thinking."

  - type: textarea
    id: feature
    attributes:
      label: Describe the feature
      placeholder: "What should we add? How would it work?"
    validations:
      required: true

  - type: textarea
    id: why
    attributes:
      label: Why is this needed?
      placeholder: "Explain how this helps users or solves a problem."
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional context or mockups
      placeholder: "Add any drawings, links, or extra thoughts here..."
